# Deployment manifest below
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3 # Let's say we want 3 NGINX Pods
  selector:
    matchLabels:
      app: nginx # This must match the Service's selector!
  template:
    metadata:
      labels:
        app: nginx # This label makes the Pod discoverable by the Service
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80 # The NGINX container listens on port 80

# Service manifest below
apiVersion: v1
kind: Service
metadata:
  name: my-nginx-service  # Name of the Service
spec:
  selector:
    app: nginx            # Selects Pods with the label 'app: nginx'
  ports:
    - protocol: TCP
      port: 80            # Port the Service exposes (this is the port other services will connect to)
      targetPort: 80      # Port on the Pod that the Service will forward traffic to
  type: ClusterIP         # Explicitly declares the Service type as ClusterIP (it's the default)
