kind: ReplicationController          #instead of pod           
apiVersion: v1
metadata:
  name: myreplica
spec:
  replicas: 2            
  selector:        
    myname: Dhruv                    #like a label                        
  template:                          #template for a new pod that will be created    
    metadata:
      name: testpod6
      labels:            
        myname: Dhruv                #to match selector
    spec:
     containers:
       - name: c00
         image: ubuntu
         command: ["/bin/bash", "-c", "while true; do echo Hello-Bhupinder; sleep 5 ; done"]  
